### ISSUE TITLE
Vertical mode and Custom metrix. 

### ISSUE THREAD

**Issue by NoroNetwork** [justr0st/esphome-RGB-LED-pixel-clock#1]
Helloooo :) 

Great Project. 

Is there way to edit this to suport custom metrix?

I am triing to edit code to work on 11x7 vertical metrix. 

So my output would be: 
1 0. -- Hours
2 3 -- Minutes
Without devider. 

Bitmat is OK its working and code to but i cant understand how to edit to work in vertical. 

Thanks for great project :)

**Comment by justr0st** [comment]
Hello there! 
Thanks for the appreciation and following the project!

First of all, I think you mean the matrix 7x11 (horizonal x vertical pixels), right? Then you heed to redefine the display matrix in "display" section by changing width and height accordingly. 
Second thing to do is finding out, what exactly your matrix is and how your pixels are mapped. In case you have followed my project and also went using adressable led light, you don't need to change the platform. However it is very important to set the pixel_mapper correct. If your every second row has inverse pixel order like mine, then it should be enough to change 17->7 and 16->6 in the pixel_mapper.
```
  display:
    - platform: addressable_light
      id: led_matrix_display
      addressable_light_id: led_matrix
      width: 7
      height: 11
      pixel_mapper: |-
        if (y % 2 == 0) {
          return (y * 7) + x;
        }
        return (y * 7) + (6 - x);
```
However if your strips are vertical or in some other order, you should do some math 🙂. See [ESPHome Adressable Light](https://esphome.io/components/display/addressable_light.html) for reference.

I changed the code in the YAML today so the next things you will need are now already supported:

1. Update the digits coordinates in digit_location_X and digit_location_Y arrays. They are the coordinates of the upper left pixel of each digit. In your case i think it should be like that:
```
          const int digit_location_X[digitsCount] = {0, 4, 0, 4};
          const int digit_location_Y[digitsCount] = {0, 0, 6, 6};
```

2. Disable colon symbol:
```
          const bool enableColon = false;`
```


I think that schould do.

**Comment by NoroNetwork** [comment]
Oh great. This works. 

Thanks for the expenation :)

**Comment by NoroNetwork** [comment]
Closing :)

**Comment by justr0st** [comment]
You are welcome :)
